name: Build
on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: get_tag
        run:  TAG=${GITHUB_SHA::7}; echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Print result
        run: exit 0
