name: Deploy-prod
on:
  workflow_dispatch:
  
jobs:
  Deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deploy_dev_conclusion == 'success' }}
    steps:
      - name: Deploy
        run: echo ${{ tojson(github) }}
