name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Data
        run: echo "Event: ${{ toJson(github.event) }}"
