name: Conditional Step Example
on:
  push:
    branches:
      - main
env:
  CMD: ''
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print CMD
        run: echo ${{ env.CMD }}

      - name: Step with condition ==
        if: ${{ env.CMD == '' }}
        run: echo "The command is empty"
        
      - name: Step with condition !=
        if: ${{ env.CMD != '' }}
        run: echo "The command is NOT empty"
