name: Example Workflow
on:
    workflow_dispatch:
  

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check_changes
        id: check_changes
        run: |
          git fetch origin
          CHANGES=$(git diff --name-only origin/${{ github.event.repository.default_branch }})
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV

      - name: prompt_confirmation
        uses: actions/github-script@v6
        with:
          script: |
            const changes = process.env.CHANGES;
            if (changes) {
              const response = await github.rest.repos.createDispatchEvent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                event_type: 'confirm-build',
                client_payload: { changes }
              });
              return response;
            } else {
              return { message: 'No changes detected' };
            }
      - name: wait_for_confirmation
        uses: actions/github-script@v6
        with:
          script: |
            const { data: { state } } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });
            if (state !== 'completed') {
              throw new Error('Build not confirmed');
            }
      - name: docker_build
        run:  echo "docker build -t image name ."
