name: Conditional Step Example
on:
  push:
    branches:
      - main
env:
  CMD: somecommand
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print CMD
        run: echo ${{ env.CMD }}

      - name: Step with condition
        if: ${{ env.CMD && env.CMD.length > 4 }}
        run: echo "The command has more than 4 characters:${{ env.CMD }}"
