name: Print Repository Name
on: [push, workflow_dispatch]

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_ip: ${{vars.HOSTS}}
    steps:
      - name: Print HOST IP
        run: echo "${{ matrix.node_ip }}"
