name: Print Repository Name
on: [push, workflow_dispatch]
env:
  HOSTS: "[11, 22]"
jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_ip: ${{ fromJson(env.HOSTS) }}
    steps:
      - name: Print HOST IP
        run: echo "${{matrix.node_ip}}"
