name: Print Repository Name
on: [push, workflow_dispatch]

jobs:
  print-repo-name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_ip: [ 10.0.0.57, 10.0.16.104 ]
    steps:
      - name: Print HOST IP
        run: echo "${{ fromJson(matrix.node_ip) }}"
