name: Conditional Step Example
on:
  push:
    branches:
      - dddd
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print CMD
        run: echo ${{ vars.CMD }}

      - name: Step with condition ==
        if: ${{ vars.CMD == 'no' }}
        run: echo "The command is empty"
        
      - name: Step with condition !=
        if: ${{ vars.CMD != 'no' }}
        run: echo "The command is NOT empty"
